package com.covid19.dataStructures

object stateNameConstants {
  final val AndamanAndNicobarIslands = "Andaman and Nicobar Islands"
  final val AndhraPradesh = "Andhra Pradesh"
  final val ArunachelPradesh = "Arunachal Pradesh"
  final val Assam = "Assam"
  final val Bihar = "Bihar"
  final val Chhattisgarh = "Chhattisgarh"
  final val Chandigarh = "Chandigarh"
  final val DadraAndNagarHaveli = "Dadra and Nagar Haveli"
  final val DamanAndDiu = "Daman and Diu"
  final val Delhi = "Delhi"
  final val Goa = "Goa"
  final val Gujarat = "Gujarat"
  final val Haryana = "Haryana"
  final val HimachalPradesh = "Himachal Pradesh"
  final val JammuAndKashmir = "Jammu and Kashmir"
  final val Jharkhand = "Jharkhand"
  final val Karnataka = "Karnataka"
  final val Kerala = "Kerala"
  final val Ladakh = "Ladakh"
  final val Lakshadweep = "Lakshadweep"
  final val MadhyaPradesh = "Madhya Pradesh"
  final val Maharashtra = "Maharashtra"
  final val Manipur = "Manipur"
  final val Meghalaya = "Meghalaya"
  final val Mizoram = "Mizoram"
  final val Nagaland = "Nagaland"
  final val Orissa = "Orissa"
  final val Pondicherry = "Pondicherry"
  final val Punjab = "Punjab"
  final val Rajasthan = "Rajasthan"
  final val Sikkim = "Sikkim"
  final val TamilNadu = "Tamil Nadu"
  final val Telangana = "Telangana"
  final val Tripura = "Tripura"
  final val Uttarakhand = "Uttarakhand"
  final val UttarPradesh = "Uttar Pradesh"
  final val WestBengal = "West Bengal"

}
